version: 2

# Specify Node.js directly under build tools without the os key
build:
  tools:
    nodejs: "18"  # Specify the Node.js version compatible with Angular 17

# Specify commands for building the Angular project
commands:
  - npm install  # Install Angular, Firebase, and CometChat dependencies
  - npm run build  # Build the Angular project

# Define the documentation output formats
formats: 
  - htmlzip
  - pdf
  - epub

# Set up any environment variables needed for Firebase and CometChat
env:
  - FIREBASE_API_KEY=your-firebase-api-key
  - FIREBASE_PROJECT_ID=your-firebase-project-id
  - COMETCHAT_APP_ID=your-cometchat-app-id
  - COMETCHAT_REGION=your-cometchat-region
