version: 2

# The documentation builder
sphinx:
  version: 4.5.0  # Specify the Sphinx version you are using
  configuration: docs/conf.py  # Path to your Sphinx configuration file

# Python requirements file
python:
  install:
    - requirements: docs/requirements.txt  # If you have dependencies, create this file

# Specify the OS for the build
build:
  os: ubuntu-22.04  # Specify a supported OS
  tools:
    sphinx:  # This indicates that Sphinx should be used to build the documentation
      version: 4.5.0  # Specify the Sphinx version you are using

# The path to the documentation source
formats: 
  - htmlzip
  - pdf
  - epub
