version: 2

# Specify the OS and Node.js version for the build
build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"  # Specify the Node.js version compatible with Angular 17

# The dependencies and build commands for Node.js
build:
  commands:
    - npm install  # Install Angular and Firebase dependencies
    - npm run build  # Build the Angular project

# Output formats for the documentation
formats: 
  - htmlzip
  - pdf
  - epub

# Set environment variables for Firebase and CometChat, if needed
env:
  - FIREBASE_API_KEY=your-firebase-api-key
  - FIREBASE_PROJECT_ID=your-firebase-project-id
  - COMETCHAT_APP_ID=your-cometchat-app-id
  - COMETCHAT_REGION=your-cometchat-region
