version: 2

# Specify the OS and Node.js version for the build
build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"  # Replace with the correct Node.js version as needed for Angular 17

# Commands to install dependencies and build the Angular project
commands:
  - npm install  # Install project dependencies, including Angular, Firebase, and CometChat
  - npm run build  # Build the Angular project; adjust if your project uses a different build command

# Output formats for the documentation
formats: 
  - htmlzip
  - pdf
  - epub

# Documentation directory and Sphinx configuration (optional for Angular)
sphinx:
  configuration: docs/conf.py  # Only include this if using Sphinx for documentation generation; otherwise, omit or specify an Angular-compatible tool.

# Additional environment variables, if needed for Firebase or CometChat
env:
  - FIREBASE_API_KEY: "your-firebase-api-key"
  - FIREBASE_PROJECT_ID: "your-firebase-project-id"
  - COMETCHAT_APP_ID: "your-cometchat-app-id"
  - COMETCHAT_REGION: "your-cometchat-region"
